import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { CartProvider } from "@/context/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Andromeda Coffee</title>
        <link rel="stylesheet" href="https://use.typekit.net/skx1gnd.css" />
      </head>
      <body className={inter.className + " bg-white"}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
